### ISSUE TITLE
Looking for example clock faces

### ISSUE THREAD

**Issue by colacoos** [osisoft/OCS-Docs#573]
Looking for example clock faces

__Originally posted by @sandcrawlers in https://github.com/orff/OpenClockStandard/issues/1__

**Comment by colacoos** [comment]
I was send here by the app "Clockology" to get information on how to get a selfmade or already made by others on my AppleWatch 6. It turns out you have to be a qualified programmer to do so. I paid a lot of money for an application and that's so user unfriendly I give up and cancel my subscription. Not your fault but know they refer to your code and spread misinformation when they sell this app "Clockology"

**Comment by cmanhard** [comment]
You are commenting in site unrelated to your search or interest.
